### ISSUE TITLE
dmdtask: Failure when uploading file.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#261]
When I try to upload "MasterFile_Serials.mrc" from the samples, I'm told it is uploaded but a new document isn't created in the `dmdtask` database.

I then looked at the logs and found that the server had exit, and I needed to restart.

```
[17:33] root@iris access# docker-compose logs -f
Attaching to access_admin_1, access_lapin_1
admin_1  | 
admin_1  | > @crkn-rcdr/admin@0.0.0 start /repo/services/admin
admin_1  | > node ./dist/index.js
admin_1  | 
admin_1  | Listening on 0.0.0.0:4747
lapin_1  | 
lapin_1  | > @crkn-rcdr/lapin@0.0.0 start /repo/services/lapin
lapin_1  | > node ./dist/server.js
lapin_1  | 
lapin_1  | Starting lapin on port 5858.
admin_1  | node:internal/errors:463
admin_1  |     ErrorCaptureStackTrace(err);
admin_1  |     ^
admin_1  | 
admin_1  | RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: ERR_HTTP_INVALID_STATUS_CODE
admin_1  |     at new NodeError (node:internal/errors:370:5)
admin_1  |     at ServerResponse.writeHead (node:_http_server:275:11)
admin_1  |     at ServerResponse.writeHead (file:///repo/services/admin/dist/index.js:19503:26)
admin_1  |     at ServerResponse._implicitHeader (node:_http_server:266:8)
admin_1  |     at ServerResponse.end (file:///repo/services/admin/dist/index.js:19653:14)
admin_1  |     at Polka.onError (file:///repo/services/admin/dist/index.js:19871:9)
admin_1  |     at next (file:///repo/services/admin/dist/index.js:19935:42)
admin_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
admin_1  |   code: 'ERR_HTTP_INVALID_STATUS_CODE'
admin_1  | }
admin_1  |  ERROR  Command failed with exit code 1.
access_admin_1 exited with code 1
admin_1  | 
admin_1  | > @crkn-rcdr/admin@0.0.0 start /repo/services/admin
admin_1  | > node ./dist/index.js
admin_1  | 
admin_1  | Listening on 0.0.0.0:4747
```

I tried with a different file and got similar.

This is when running docker.c7a.ca/access-platform:20210820204148  
https://github.com/crkn-rcdr/Systems-Administration/issues/297

**Comment by RussellMcOrmond** [comment]
This may be helpful.

```
russell@russell-XPS-13-7390:~/git/Access-Platform$ git diff
diff --git a/.env.dev b/.env.dev
index d60930a..29bdf51 100644
--- a/.env.dev
+++ b/.env.dev
@@ -6,3 +6,4 @@ SWIFT_URL=http://172.30.0.54:8080
 SWIFT_USER=test
 SWIFT_PASSWORD=test
 SWIFT_ACCOUNT=AUTH_test
+NODE_ENV=production
russell@russell-XPS-13-7390:~/git/Access-Platform$ NODE_ENV=production pnpm build

> @crkn-rcdr/access-platform@0.0.0 build /home/russell/git/Access-Platform
> pnpm clean && pnpm install && pnpm build -r --filter ./packages


> @crkn-rcdr/access-platform@0.0.0 clean /home/russell/git/Access-Platform
> pnpm clean -r

Scope: all 9 workspace projects
packages/data clean$ rm -rf dist
└─ Done in 14ms
packages/env clean$ rm -rf dist
└─ Done in 14ms
packages/couch-utils clean$ rm -rf dist
└─ Done in 9ms
packages/swift clean$ rm -rf dist
└─ Done in 9ms
packages/lapin-router clean$ rm -rf dist
└─ Done in 6ms
services/admin clean$ rm -rf .svelte-kit dist
└─ Done in 10ms
services/lapin clean$ rm -rf dist
└─ Done in 9ms
Scope: all 9 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
Scope: 5 of 9 workspace projects
packages/data build$ npm-run-all clean --parallel build:*
│ sh: 1: npm-run-all: not found
└─ Running...
packages/env build$ npm-run-all clean --parallel build:*
│ sh: 1: npm-run-all: not found
└─ Running...
/home/russell/git/Access-Platform/packages/env:
 ERROR  @crkn-rcdr/access-env@0.0.1 build: `npm-run-all clean --parallel build:*`
spawn ENOENT
 ERROR  Command failed with exit code 1.
russell@russell-XPS-13-7390:~/git/Access-Platform$ 

```
