### ISSUE TITLE
access: <h1>500: _ is not defined</h1>

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#541]
While the Javascript renders the page correctly for staff, there are problems in what is sent.

Example: https://access.canadiana.ca/object/edit/69429/m0pg1hh6j404

Looking at the network in the developer tools I see a  "500" status page.

It the only file of type "document", and appears to be what is loading the app.  I'm surprised this works, but apparently it does.

**Comment by RussellMcOrmond** [comment]
Looked at the docker logs (there are a lot of logs being generated).

```
access-admin-1  | ReferenceError: _ is not defined
access-admin-1  |     at checkModelChanged (file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:887:3)
access-admin-1  |     at checkValidDiff (file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:900:27)
access-admin-1  |     at checkEnableSave (file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:960:21)
access-admin-1  |     at file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:975:9
access-admin-1  |     at Object.$$render (file:///repo/services/admin/dist/server/chunks/index-379b020f.js:268:18)
access-admin-1  |     at Object.default (file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:1380:59)
access-admin-1  |     at file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:124:85
access-admin-1  |     at Object.$$render (file:///repo/services/admin/dist/server/chunks/index-379b020f.js:268:18)
access-admin-1  |     at Object.side-menu-header (file:///repo/services/admin/dist/server/chunks/Editor-ccad2337.js:1374:58)
access-admin-1  |     at file:///repo/services/admin/dist/server/chunks/SideMenuContainer-ad0b0d7a.js:100:137
```
