### ISSUE TITLE
access-admin: ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#560]
If I go to https://access.canadiana.ca/object/edit/69429/g0v11vd6pc3q

On the console (docker-compose logs) I see:

```
access-admin-1  | 2022-11-22T21:38:41.416701142Z ReferenceError: _ is not defined
access-admin-1  | 2022-11-22T21:38:41.416750045Z     at checkModelChanged (file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:890:3)
access-admin-1  | 2022-11-22T21:38:41.416757238Z     at checkValidDiff (file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:903:27)
access-admin-1  | 2022-11-22T21:38:41.416762888Z     at checkEnableSave (file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:958:21)
access-admin-1  | 2022-11-22T21:38:41.416768262Z     at file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:969:7
access-admin-1  | 2022-11-22T21:38:41.416773875Z     at Object.$$render (file:///repo/services/admin/dist/server/chunks/index-379b020f.js:268:18)
access-admin-1  | 2022-11-22T21:38:41.416779288Z     at Object.default (file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:1509:59)
access-admin-1  | 2022-11-22T21:38:41.416784313Z     at file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:125:85
access-admin-1  | 2022-11-22T21:38:41.416789295Z     at Object.$$render (file:///repo/services/admin/dist/server/chunks/index-379b020f.js:268:18)
access-admin-1  | 2022-11-22T21:38:41.416794315Z     at Object.side-menu-header (file:///repo/services/admin/dist/server/chunks/Editor-7acf2574.js:1503:58)
access-admin-1  | 2022-11-22T21:38:41.416801069Z     at file:///repo/services/admin/dist/server/chunks/SideMenuContainer-ad0b0d7a.js:100:137
```

**Comment by RussellMcOrmond** [comment]
```
access-admin-1  | 2023-01-30T15:21:13.874544253Z ReferenceError: _ is not defined
access-admin-1  | 2023-01-30T15:21:13.874611436Z     at checkModelChanged (file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:884:3)
access-admin-1  | 2023-01-30T15:21:13.874631464Z     at checkValidDiff (file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:897:27)
access-admin-1  | 2023-01-30T15:21:13.874643189Z     at checkEnableSave (file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:952:21)
access-admin-1  | 2023-01-30T15:21:13.874653884Z     at file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:963:7
access-admin-1  | 2023-01-30T15:21:13.874665023Z     at Object.$$render (file:///repo/services/admin/dist/server/chunks/index-379b020f.js:268:18)
access-admin-1  | 2023-01-30T15:21:13.874675598Z     at Object.default (file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:1508:59)
access-admin-1  | 2023-01-30T15:21:13.874686873Z     at file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:126:85
access-admin-1  | 2023-01-30T15:21:13.874697642Z     at Object.$$render (file:///repo/services/admin/dist/server/chunks/index-379b020f.js:268:18)
access-admin-1  | 2023-01-30T15:21:13.874707789Z     at Object.side-menu-header (file:///repo/services/admin/dist/server/chunks/Editor-18176d6f.js:1502:58)
access-admin-1  | 2023-01-30T15:21:13.874718301Z     at file:///repo/services/admin/dist/server/chunks/SideMenuContainer-ad0b0d7a.js:100:137
```
